[project]
name = "social-app-beta"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rioreyblue", email = "franciscorey702@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastapi-users[sqlalchemy]>=15.0.5",
    "fastapi[standard]>=0.141.0",
    "imagekitio>=5.8.0",
    "python-dotenv>=1.2.2",
    "uvicorn[standard]>=0.52.0",
]

[project.scripts]
social-app-beta = "social_app_beta:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
